### ISSUE TITLE
Failed deserialization of io.camunda.connector.common.auth.Authentication in connector-http-json

### ISSUE THREAD

**Issue by m-myska** [camunda/connectors#1104]
__Describe the Bug__
When zeebe-play and connectors bundle are running locally in Docker containers on Windows 10 then the REST connector activity with following definitions fails:
```
        <zeebe:taskDefinition type="io.camunda:http-json:1" />
        <zeebe:ioMapping>
          <zeebe:input source="basic" target="authentication.type" />
          <zeebe:input source="post" target="method" />
          <zeebe:input source="https://es.local/zeebe-record-variable/_search" target="url" />
          <zeebe:input source="{{secrets.ELASTICSEARCH_USER}}" target="authentication.username" />
          <zeebe:input source="{{secrets.ELASTICSEARCH_PASSWORD}}" target="authentication.password" />
          <zeebe:input source="60" target="connectionTimeoutInSeconds" />
          <zeebe:input source="={&#10;  &#34;query&#34;: {&#10;    &#34;bool&#34;: {&#10;      &#34;filter&#34;: [&#10;        { &#34;term&#34;: { &#34;value.bpmnProcessId&#34;: &#34;Test&#34; } },&#10;        { &#34;term&#34;: { &#34;value.name&#34;: &#34;lastId&#34; } }&#10;      ]&#10;    }&#10;  },&#10;  &#34;sort&#34;: [ { &#34;timestamp&#34;: { &#34;order&#34;: &#34;desc&#34; } } ],&#10;  &#34;size&#34;: 1&#10;}" target="body" />
        </zeebe:ioMapping>
```
```
INFO 1 --- [pool-2-thread-2] i.c.c.r.c.outbound.ConnectorJobHandler   : Received job 2251799813853017
ERROR 1 --- [pool-2-thread-2] i.c.c.r.c.outbound.ConnectorJobHandler   : Exception while processing job 2251799813853017

io.camunda.connector.api.error.ConnectorException: Error during json mapping.
        at io.camunda.connector.runtime.core.outbound.JobHandlerContext.mapJson(JobHandlerContext.java:77)
        at io.camunda.connector.runtime.core.outbound.JobHandlerContext.bindVariables(JobHandlerContext.java:60)
        at io.camunda.connector.http.HttpJsonFunction.execute(HttpJsonFunction.java:68)
        at io.camunda.connector.runtime.core.outbound.ConnectorJobHandler.handle(ConnectorJobHandler.java:105)
        at io.camunda.connector.runtime.outbound.jobhandling.SpringConnectorJobHandler.lambda$handle$0(SpringConnectorJobHandler.java:71)
        at io.micrometer.core.instrument.AbstractTimer.record(AbstractTimer.java:247)
        at io.camunda.zeebe.spring.client.actuator.MicrometerMetricsRecorder.executeWithTimer(MicrometerMetricsRecorder.java:52)
        at io.camunda.connector.runtime.outbound.jobhandling.SpringConnectorJobHandler.handle(SpringConnectorJobHandler.java:62)
        at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44)
        at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

When I debug `JobHandlerContext.mapJson` it fails on the following exception:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.camunda.connector.common.auth.Authentication` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
at [Source: (String)"{"url":"https://es.local/zeebe-record-variable/_search","body":{"query":{"bool":{"filter":[{"term":{"value.bpmnProcessId":"Test"}},{"term":{"value.name":"lastId"}}]}},"sort":[{"timestamp":{"order":"desc"}}],"size":1},"method":"post","authentication":{"type":"basic","username":"elastic","password":"elastic"},"connectionTimeoutInSeconds":"60"}"; line: 1, column: 285] (through reference chain: io.camunda.connector.http.model.HttpJsonRequest["authentication"])
```

__Steps to Reproduce__

1. start zeebe-play: `docker run -p 8080:8080 -p 26500:26500 ghcr.io/camunda-community-hub/zeebe-play:latest`
2. build and start connectors bundle: `docker run -it --rm -p 5005:5005 --env-file connector.properties camunda-connectors:test`
**Dockerfile**:
```
ARG CAMUNDA_CONNECTORS_VERSION=0.22.1
FROM camunda/connectors:${CAMUNDA_CONNECTORS_VERSION}
ARG CAMUNDA_CONNECTORS_VERSION
ADD https://repo1.maven.org/maven2/io/camunda/connector/connector-http-json/${CAMUNDA_CONNECTORS_VERSION}/connector-http-json-${CAMUNDA_CONNECTORS_VERSION}-with-dependencies.jar /opt/app/
USER root
```
**connector.properties**: 
```
zeebe.client.broker.gatewayAddress=host.docker.internal:26500
zeebe.client.security.plaintext=true
zeebe.client.worker.default-name=camunda-connectors
camunda.connector.polling.enabled=false
operate.client.enabled=false
JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
```
3. Deploy process with `io.camunda:http-json:1` activity to zeebe play and run the process

__Expected Behavior__
io.camunda.connector.http.model.HttpJsonRequest object supposed to be de-serialized.

__Environment__

- OS: Windows 10
- Connectors version: 0.22.1
- Camunda version:  8.2.x

**Comment by sbuettner** [comment]
Hey @slolatte would be great if you could check agains our SaaS runtime whether basic authentication is working or whether this might be a regression. Thank you!

**Comment by slolatte** [comment]
@sbuettner on SaaS Integration with cluster (connectors 0.23), basic authentication is working as expected with the REST connector.

**Comment by sbuettner** [comment]
@m-myska As this was tested and verified I would close this issue for now. Please let us know if you have more details.
