### ISSUE TITLE
Zeebe client can't write credentials cache (when running in Docker)

### ISSUE THREAD

**Issue by chillleader** [camunda/connectors#1613]
__Describe the Bug__

When running the Connectors docker image built from any Dockerfile in this repo, the Zeebe client attempts to cache client credentials in a file located in `/home/connectors` and fails due to missing permissions.

This results in the following log messages:
```
io.grpc.StatusRuntimeException: CANCELLED
                <part of the stacktrace omitted>
Caused by: java.nio.file.AccessDeniedException: /home/camunda
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
        at java.base/java.nio.file.Files.createDirectory(Unknown Source)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
        at java.base/java.nio.file.Files.createDirectories(Unknown Source)
        at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsCache.ensureCacheFileExists(OAuthCredentialsCache.java:147)
        at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsCache.writeCache(OAuthCredentialsCache.java:74)
        at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsCache.computeIfMissingOrInvalid(OAuthCredentialsCache.java:101)
        at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsProvider.applyCredentials(OAuthCredentialsProvider.java:84)
        at io.camunda.zeebe.client.impl.ZeebeCallCredentials.lambda$applyRequestMetadata$0(ZeebeCallCredentials.java:48)
        ... 3 common frames omitted

```

The bug can be fixed by applying the following envioronment variable:
```ZEEBE_CLIENT_CONFIG_PATH=/tmp/connectors```

Note that `/tmp` should be used as home directories are write protected in the container file system.

__Steps to Reproduce__

1. Get or build the Connectors Docker image (e.g. build one locally from the Dockerfile in `bundle/default-bundle`)
2. Run a container against a self managed Camunda 8 installation (with keycloak)
3. Observe the messages above in the logs

__Expected Behavior__

Credentials are cached in a location that is not write protected, e.g. `/tmp/connectors`.

__Environment__

- Camunda version: 8.3.* / 8.4.0-alpha2

**Comment by chillleader** [comment]
It seems that Zeebe client behaves like this:

- When Zeebe credentials are first obtained, they are (1) stored in-memory and (2) attempted to be written into a file.
- If (2) fails, an exceptions is raised, however the credentials are still available in the in-memory cache.
- When the call is retried, the readCache method first checks if the file exists, and if it doesn't - the in-memory cache is returned as a fallback (see [impl](https://github.com/camunda/zeebe/blob/6c3ddfcbc4d5f56a7a8a813983f368ab638eefc4/clients/java/src/main/java/io/camunda/zeebe/client/impl/oauth/OAuthCredentialsCache.java#L58))
- The issue is only observed when credentials in the in-memory cache are expired (i.e. strictly once every 5 minutes in my case).
- The outcome is that we see this issue randomly once every 5 minutes.
    - Most likely it has no impact if it happens during the job worker polling (it is auto-retried)
    - But this can also happen during an inbound connector method call that doesn't expect this kind of error (which is much less likely the the first scenario but still possible). In that case this will lead to an error in inbound connector.

I tried setting the cache file location to /tmp/connectors instead of /home/connectors and it solved the issue. (edited)
