### ISSUE TITLE
Connector doesn't evaluate FEEL expression in Queue name field of RabbitMQ inbound connector template

### ISSUE THREAD

**Issue by igor-msk** [camunda/connectors#2833]
__Describe the Bug__
A FEEL expression in Queue name field of RabbitMQ inbound connector template gets passed to RabbitMQ without being evaluated/resolved first

__Steps to Reproduce__
Put this into Queue name field of RabbitMQ inbound connector template
`=if "{{secrets.ENVIRONMENT}}" = "Prod" then "A" else "B"`

__Expected Behavior__
Queue name is either A or B
Instead I get an error in the log
`Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue '=if "Test" = "Prod" then "A" else "B"' in vhost '/', class-id=60, method-id=20)`

__Environment__
- Camunda connectors version: 8.5.3 self-managed

full log message attached:
```
2024-07-10T19:31:37.627Z  INFO 1 --- [   scheduling-1] i.c.c.r.inbound.RabbitMqExecutable       : Subscription activation requested by the Connector runtime: RabbitMqInboundProperties{authentication=UriAuthentication[uri=amqp://SBF.CAM.User-Test:XXX@Test-rabbitmq.sberfactoring.ru], routing=null, queueName='=if "Test" = "Prod" then "A" else "B"', consumerTag='sbf-it-cam-dockerwebservice-connectors-54bbb9b48c-6mv7d', arguments=null, exclusive=false}
2024-07-10T19:31:37.669Z ERROR 1 --- [   scheduling-1] i.c.c.r.i.l.InboundConnectorManager      : Failed to activate inbound connector InboundConnectorDefinitionImpl{correlationPoint=MessageStartEventCorrelationPoint[messageName=3b679faf-7776-49fc-9715-e4c94be6a13a, messageIdExpression=null, correlationKeyExpression=null, bpmnProcessId=BidFactoring1C, version=11, processDefinitionKey=2251799814084091], bpmnProcessId='BidFactoring1C', version=11, processDefinitionKey=2251799814084091, elementId='startEvent_messageFrom1C, tenantId='<default>'}

java.io.IOException: null
        at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:140)
        at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:136)
        at com.rabbitmq.client.impl.ChannelN.basicConsume(ChannelN.java:1408)
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicConsume(AutorecoveringChannel.java:543)
        at io.camunda.connector.rabbitmq.inbound.RabbitMqExecutable.startConsumer(RabbitMqExecutable.java:100)
        at io.camunda.connector.rabbitmq.inbound.RabbitMqExecutable.activate(RabbitMqExecutable.java:61)
        at io.camunda.connector.runtime.inbound.lifecycle.InboundConnectorManager.activateConnector(InboundConnectorManager.java:147)
        at io.camunda.connector.runtime.inbound.lifecycle.InboundConnectorManager.handleNewProcessDefinitions(InboundConnectorManager.java:97)
        at io.camunda.connector.runtime.inbound.importer.ProcessDefinitionImporter.handleImportedDefinitions(ProcessDefinitionImporter.java:113)
        at io.camunda.connector.runtime.inbound.importer.ProcessDefinitionImporter.scheduleImport(ProcessDefinitionImporter.java:60)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124)
        at io.micrometer.observation.Observation.observe(Observation.java:499)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue '=if "Test" = "Prod" then "A" else "B"' in vhost '/', class-id=60, method-id=20)
        at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
        at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
        at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:552)
        at com.rabbitmq.client.impl.ChannelN.basicConsume(ChannelN.java:1402)
        ... 20 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue '=if "Test" = "Prod" then "A" else "B"' in vhost '/', class-id=60, method-id=20)
        at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:528)
        at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:349)
        at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:193)
        at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:125)
        at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:761)
        at com.rabbitmq.client.impl.AMQConnection.access$400(AMQConnection.java:48)
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:688)
        ... 1 common frames omitted
```

**Comment by sbuettner** [comment]
@igor-msk Thanks for raising this. Similar to the Kafka Connector we removed support for FEEL expressions for some inbound Connector properties as it was misleading to users. For now I would recommend you to just pass the queue name using a secret value.
