### ISSUE TITLE
[8.3] Duplicate inbound Connector config properties lead to exceptions

### ISSUE THREAD

**Issue by sbuettner** [camunda/connectors#2834]
__Describe the Bug__

The process definition imports throws an exception if it detects multiple properties with the same name:

 ```
Failed to import process definitions java.lang.RuntimeException: java.lang.IllegalStateException: Duplicate key approver (attempted merging values XXX and YYY) 	at io.camunda.connector.runtime.inbound.lifecycle.InboundConnectorManager.lambda$handleNewProcessDefinitions$1(InboundConnectorManager.java:83)
at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(Unknown Source)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source
```

__Steps to Reproduce__

Add an inbound Connector element to a BPMN model and duplicate a single property with two different values.

Example logs can be found here: : https://camunda.slack.com/archives/C067UQ6M9EE/p1720686048208539

__Expected Behavior__

No exceptions should be thrown when an import detects an illegal inbound Connector configuration. A log entry with severity `WARNING` is sufficient.

__Environment__

- Camunda version: 8.3.12

**Comment by chillleader** [comment]
The process import will be retried until the faulty BPMN is replaced, root cause is [here](https://github.com/camunda/connectors/blob/03d539d08b8138b3bc8bb1d5c845d669927c4557/connector-runtime/connector-runtime-spring/src/main/java/io/camunda/connector/runtime/inbound/lifecycle/InboundConnectorManager.java#L83). This has been last changed in [this PR](https://github.com/camunda/connectors/pull/1883). Before that PR, failures have been ignored, which is also a bad strategy as something like a broken Operate connection can stop the processing.
We might need a more elaborate error handling approach here and differentiate between Operate and non-Operate errors.

**Comment by sbuettner** [comment]
Related issue https://github.com/camunda/camunda-modeler/issues/4357

**Comment by sbuettner** [comment]
Duplicate of https://github.com/camunda/connectors/2939
